# Generated by Django 3.1.5 on 2021-03-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210125_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='votes',
            new_name='values',
        ),
    ]
